#version: '3'
services:
  #estanteCriticaApi:
    #image: mongodb/mongodb-community-server:6.0.14-ubi9
    #environment:
    #  - CONN_STR=mongodb://user:pass@mongodb
    #command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    #depends_on:
     # - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0.14-ubi9
    container_name: mongodb_container
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
#      - CONN_STR=mongodb://user:pass@mongodb
#      - MONGODB_INITDB_DATABASE=estantedb
    networks:
      - db_network
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
      - ./scripts/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  db_network:
    name: mongodb_network